defaults: &defaults
  host: localhost

development:
  <<: *defaults
  database: dev

test:
  <<: *defaults
  database: test

uat:
  <<: *defaults
  database: uat

production:
  host: 10.10.5.54 
  database: production
