defaults: &defaults
  host: 10.10.5.54

development:
  <<: *defaults
  database: production

test:
  <<: *defaults
  database: test

uat:
  <<: *defaults
  database: uat

production:
  <<: *defaults
  database: production
